---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control

appservers:
  hosts:
    # appserver-vm:
    #   ansible_host: appserver
    # frontend-vm:
    #   ansible_host: frontserver
    azure-app-server:
      ansible_host: devopsvm

dbservers:
  hosts:
    # dbserver-vm:
    #     ansible_host: dbserver
    azure-db-server:
        ansible_host: devopsdb

k8sservers:
  hosts:
    azure-k8s-server:
      ansible_host: devopsk8s