app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: appuser
    spring.datasource.password: apppassword
    spring.datasource.url: jdbc:mysql://10.0.0.4:3306/appdb

service:
  workingdir: "{{ ansible_user_dir }}/spring"
  execstart: "java -jar target/dev_ops-0.0.1-SNAPSHOT.jar"