---
- hosts: k8sservers
  tasks:

  # - name: Check if microk8s is installed
  #   ansible.builtin.shell: microk8s version
  #   register: k8s_version_result
  #   ignore_errors: true
  #   become: yes

  # - name: Set k8s installed fact
  #   set_fact:
  #   k8s_installed: "{{ k8s_version_result.rc == 0 }}"

  - name: "Clone the Spring repository"
    git:
      repo: "https://github.com/GianniCapocci/DevOps.git"
      dest: "{{ appdir }}"
      version: "{{ branch }}"
      force: yes

  - name: "Populate application.properties"
    lineinfile:
      dest: "{{ appdir }}/src/main/resources/application.properties"
      state: present
      regexp: "^{{item.key}}="
      line: "{{item.key}}={{item.value}}"
    with_items:
      - "{{app.env | dict2items}}"

  - name: "Change tag of image from deployment"
    ansible.builtin.shell:
      '''
          HEAD_COMMIT=$(git rev-parse --short HEAD)
          TAG=$HEAD_COMMIT-$BUILD_ID
          # if we had multiple configurations in kubeconfig file, we should select the correct one
          # kubectl config use-context devops
          kubectl set image deployment/spring-deployment spring=$DOCKER_PREFIX:$TAG
          kubectl rollout status deployment spring-deployment --watch --timeout=2m
      '''